// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7QruZFpl8KnDU1mn1scSGdZhFiORIYO4',
    appId: '1:870898812239:web:c29fb6222bb48aaa54313a',
    messagingSenderId: '870898812239',
    projectId: 'test-firebase-412fc',
    authDomain: 'test-firebase-412fc.firebaseapp.com',
    storageBucket: 'test-firebase-412fc.firebasestorage.app',
    measurementId: 'G-J3NED22307',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6jiPZI0oGzWC2S3vpCAOebIQ1NVd3CPI',
    appId: '1:870898812239:android:6a2c412efaa2490454313a',
    messagingSenderId: '870898812239',
    projectId: 'test-firebase-412fc',
    storageBucket: 'test-firebase-412fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLVD1FfbTJUY60h4R5ppbDW1i3HggNEcI',
    appId: '1:870898812239:ios:9591c45033e8683454313a',
    messagingSenderId: '870898812239',
    projectId: 'test-firebase-412fc',
    storageBucket: 'test-firebase-412fc.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLVD1FfbTJUY60h4R5ppbDW1i3HggNEcI',
    appId: '1:870898812239:ios:9591c45033e8683454313a',
    messagingSenderId: '870898812239',
    projectId: 'test-firebase-412fc',
    storageBucket: 'test-firebase-412fc.firebasestorage.app',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7QruZFpl8KnDU1mn1scSGdZhFiORIYO4',
    appId: '1:870898812239:web:6c02aff6cb9da69754313a',
    messagingSenderId: '870898812239',
    projectId: 'test-firebase-412fc',
    authDomain: 'test-firebase-412fc.firebaseapp.com',
    storageBucket: 'test-firebase-412fc.firebasestorage.app',
    measurementId: 'G-9V38N9LHEH',
  );
}
